input_type: pointcloud
input_resolution: 128
input_points_number: 100000
model: TEXR
folder_name: ./pretrained_texture_regular_less_vertices
data_path: ../SHARP_data/track3
#data_path: ./track2_testdata/track3
data_bounding_box: [-0.8, 0.8, -0.15, 2.1, -0.8, 0.8]
split_file: ../SHARP_data/track2/split.npz
## Preprocessing step for evaluation set
preprocessing:
 color_sampling:
  #input_files_regex: /*_gt/*/*.obj
  sample_number: 100000
 scale_back_obj:
  mode: test
  generation_path: ../if_net/experiments/iVoxels_dist-0.5_0.5_sigmas-0.1_0.01_v32_mShapeNet32Vox_regular/
  #generation_path: ./experiments/ShapeNet32Vox
  input_files_regex: /*/*/*/*/*.off
 voxelized_colored_pointcloud_sampling:
  evaluation: True
  input_files_regex: /*/*/*-partial-*.obj
training:
 batch_size: 1
 sample_points_per_object: 50000
 optimizer: Adam
generation:
 retrieval_resolution: 256
 checkpoint: 233
 batch_points: 800000
 mode: test_texture
 retrieval_threshold: 0.5
 input_files_regex: /*/*/*/*/*.obj
 generation_files_regex: /evaluation_5_@256/generation/

