input_type: pointcloud
input_resolution: 128
input_points_number: 100000
model: TEXR
folder_name: SHARP2020_c1_t1
data_path: ./track2_testdata/track3
data_bounding_box: [-0.8, 0.8, -0.15, 2.1, -0.8, 0.8]
#split_file: ../SHARP_data/track2/split.npz
## Preprocessing step for evaluation set
preprocessing:
 scale_back_obj:
  mode: test
  generation_path: ./experiments
  input_files_regex: /*/*/*/*/*.off
 voxelized_colored_pointcloud_sampling:
  input_files_regex: /*/*/*-partial-*.obj
generation:
 retrieval_resolution: 256
 checkpoint: -1
 batch_points: 800000
 mode: test
 retrieval_threshold: 0.5

